Repository wuhan2020/wuhan2020.github.io, pull requests merged in 2020-02, with the labels that each got.

#64 Add new features
  package.json
  src/pages/home/index.jsx
Labels: don't merge

#219 Changed site-config structure
  i18n/en-us.js
  i18n/fr-fr.js
  i18n/it-it.js
  i18n/ja-jp.js
  i18n/pt-br.js
  i18n/zh-cn.js
  src/components/footer/index.jsx
  src/components/header/index.jsx
  src/components/language/index.jsx
  src/pages/blog/index.jsx
  src/pages/community/index.jsx
  src/pages/documentation/index.jsx
  src/pages/home/index.jsx
  src/pages/project/index.jsx
Labels: don't merge

#229 [Doc][Italian] FAQ
  docs/it-it/overview/faq.md
Labels: area/document

#237 [Doc][italian] FAQ translation - further corrections integration
  docs/it-it/overview/faq.md
Labels: area/document

#247 docs:update developers_dev.md
  docs/en-us/developers/developers_dev.md
  docs/fr-fr/developers/developers_dev.md
  docs/it-it/developers/developers_dev.md
  docs/ja-jp/developers/developers_dev.md
  docs/pt-br/developers/developers_dev.md
  docs/zh-cn/developers/developers_dev.md
Labels: area/document

#274 add need-questionnaire.md, close #92
  blog/zh-cn/need-questionnaire.md
  i18n/zh-cn.js
  images/blog/media/need-questionnaire-1.webp
  images/blog/media/need-questionnaire-2.webp
  images/blog/media/need-questionnaire-3.webp
Labels: kind/question

#325 Feature/apply certification
  i18n/zh-cn.js
  images/certification/illustration.png
  src/components/icon/index.scss
  src/pages/certification/certificationContent.jsx
  src/pages/certification/certificationContent.scss
  src/pages/certification/index.scss
  src/variables.scss
Labels: kind/feature
