Repository wuhan2020/wuhan2020.github.io, pull requests merged in 2020-04, with the labels that each got.

#510 Refactor Header - language component
  package.json
  src/components/LanguageList/index.jsx
  src/components/LanguageList/index.scss
  src/components/header/index.jsx
  src/components/headerNav/index.jsx
  src/components/headerNav/index.scss
  src/components/headerRefactored/index.jsx
  src/components/headerRefactored/index.scss
  src/components/logo/index.jsx
  src/components/logo/index.scss
  src/components/searchEngineSwitch/index.jsx
  src/components/searchEngineSwitch/index.scss
  src/pages/blog/index.jsx
  src/pages/blogDetail/index.jsx
  src/pages/community/index.jsx
  src/pages/documentation/index.jsx
  src/pages/hackathon/index.jsx
  src/pages/hackathonKanban/index.jsx
  src/pages/home/index.jsx
  src/pages/project/index.jsx
  template.ejs
  utils/index.js
Labels: kind/enhancement

#524 remove useless code and resort the community news
  i18n/en-us.js
  i18n/fr-fr.js
  i18n/ja-jp.js
  i18n/pt-br.js
  i18n/zh-cn.js
Labels: area/news

#531 fix: active header menu item not highlighted, fix #530
  images/blog/media/jinritoutiao.png
  images/blog/media/linkedin.jpg
  images/blog/media/twitter.jpg
  src/components/headerNav/index.jsx
  src/components/headerNav/index.scss
Labels: kind/bug
