Repository wuhan2020/wuhan2020.github.io, pull requests merged in 2020-03, with the labels that each got.

#329 [doc][italian] Contribution Guide translation and Github Repo processing proofreading
  docs/it-it/dev/contributing.md
  docs/it-it/dev/dev-env-setup.md
Labels: area/document

#334 remove force push doc
  docs/zh-cn/dev/contributing.md
Labels: area/document

#328 Feature/apply certification
  docsite.config.yml
  i18n/zh-cn.js
  images/certification/illustration.png
  src/pages/certification/certificationContent.jsx
  src/pages/certification/certificationContent.scss
  src/pages/certification/index.jsx
  src/variables.scss
Labels: kind/feature

#387 Feature kanban timer
  i18n/zh-cn.js
  src/_colors.scss
  src/_typography.scss
  src/pages/hackathonKanban/index.jsx
  src/pages/hackathonKanban/index.scss
  src/pages/hackathonKanban/kanbanTimer.jsx
  src/pages/hackathonKanban/kanbanTimer.scss
  src/variables.scss
Labels: kind/feature

#403 Feature team list
  i18n/zh-cn.js
  src/_typography.scss
  src/pages/hackathonKanban/index.jsx
  src/pages/hackathonKanban/index.scss
  src/pages/hackathonKanban/teamItem.jsx
  src/pages/hackathonKanban/teamItem.scss
Labels: kind/feature

#406 Feature team item list
  i18n/zh-cn.js
  npm-shrinkwrap.json
  package.json
  src/_colors.scss
  src/_typography.scss
  src/pages/hackathonKanban/index.jsx
  src/pages/hackathonKanban/index.scss
  src/pages/hackathonKanban/teamItem.jsx
  src/pages/hackathonKanban/teamItem.scss
  src/pages/hackathonKanban/teamItemList.jsx
  src/pages/hackathonKanban/teamItemList.scss
Labels: kind/feature

#431 update readme develop doc
  README.md
Labels: area/document

#434 Revert "update readme develop doc"
  README.md
Labels: area/document

#445 fix:
  src/components/sidemenu/index.jsx
  src/components/sidemenu/item.jsx
Labels: kind/bug

#457 fix: developers menu item highlighting issue, fix#439
  src/pages/documentation/index.jsx
Labels: kind/bug

#459 Revert "fix: developers menu item highlighting issue, fix#439"
  src/pages/documentation/index.jsx
Labels: kind/bug

#460 Revert "Revert "fix: developers menu item highlighting issue, fix#439""
  src/pages/documentation/index.jsx
Labels: kind/bug

#478 change build instrution
  README.md
Labels: bug

#471 add gitalk in docs module
  package.json
  src/pages/documentation/index.jsx
Labels: area/document, bug, help wanted, kind/feature

#482 fix_id_bug
  package.json
  src/pages/documentation/index.jsx
Labels: kind/bug

#483 Fix deploy error
  src/pages/documentation/index.jsx
Labels: kind/bug

#484 Revert "Fix deploy error"
  src/pages/documentation/index.jsx
Labels: kind/bug

#485 Revert "fix_id_bug"
  package.json
  src/pages/documentation/index.jsx
Labels: kind/bug
